# Generated by Django 3.1.6 on 2021-02-18 09:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('had_covid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT_SURE', 'Not sure')], default='NOT_SURE', max_length=8)),
                ('live_with_covid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT_SURE', 'Not sure')], default='NOT_SURE', max_length=8)),
                ('respiratory_illness', models.BooleanField()),
                ('cardiovascular_illness', models.BooleanField()),
                ('asthma', models.BooleanField()),
                ('kidney_stones', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('high_blood_pressure', models.BooleanField()),
                ('blood_disease', models.BooleanField()),
                ('cancer', models.BooleanField()),
                ('leukemia', models.BooleanField()),
                ('organ_transplant', models.BooleanField()),
                ('pregnant', models.BooleanField()),
                ('currently_employed', models.BooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.addressfield')),
            ],
        ),
    ]
