# Generated by Django 3.1.6 on 2021-02-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='region',
        ),
    ]
