# Generated by Django 3.1.6 on 2021-02-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrant',
            new_name='Individual',
        ),
    ]
