# Generated by Django 3.1.6 on 2021-02-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('registrant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.addressfield'),
        ),
    ]
