# Generated by Django 3.1.6 on 2021-02-21 17:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrant', '0002_linkaddressregistrant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='cardiovascular_illness',
            new_name='cardiovascular_disease',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='is_healthcare_worker',
            new_name='cerebrovascular_disease',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='kidney_stones',
            new_name='chronic_kidney_disease',
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='leukemia',
            new_name='down_syndrome',
        ),
        migrations.AddField(
            model_name='individual',
            name='is_frontline_personnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_frontline_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_government_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_overseas_filipino_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_teacher_or_social_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='kidney_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='priority_group',
            field=models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'A3'), (4, 'A4'), (5, 'A5'), (6, 'B1'), (7, 'B2'), (8, 'B3'), (9, 'B4'), (10, 'B5'), (11, 'B6'), (12, 'C')], default=core.models.PriorityGroup['C']),
        ),
        migrations.AddField(
            model_name='individual',
            name='seizure_disorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='sickle_cell_disease',
            field=models.BooleanField(default=False),
        ),
    ]
