# Generated by Django 3.1.6 on 2021-02-20 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernmentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registrant_map', models.FileField(blank=True, null=True, upload_to='maps/')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.addressfield')),
                ('lgu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgu.localgovernmentunit')),
            ],
        ),
    ]
